[package]
name = "allium"
version = "0.1.0"
authors = ["warms0x <warms0x@riseup.net>"]
edition = "2018"

[dependencies]
base32 = "~0.3.1"
rand = "~0.7.3"
regex = "1"
rust-crypto = "~0.2.36"
x25519-dalek = "~0.6.0"
