[package]
name = "allium"
version = "0.1.0"
authors = ["warms0x <warms0x@riseup.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
